---
- name: Configuración de la red IoT en el host manager
  hosts: manager
  become: yes
  vars:
    influxdb_version: "1.8.10"

  pre_tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalar paquetes básicos
      apt:
        name:
          - snmp
          - snmpd
        state: present
  roles: 
    - grafana
    - influxdb
    - telegraf


- name: Configuración de la red IoT en los sensores
  hosts: sensores
  become: yes

  pre_tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalar paquetes básicos
      apt:
        name:
          - snmp
          - snmpd
        state: present

  roles:
    - telegraf
    - snmp

- name: Configuración de la red IoT en las camaras
  hosts: camara
  become: yes

  pre_tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalar paquetes básicos
      apt:
        name:
          - snmp
          - snmpd
        state: present

  roles:
    - telegraf
    - snmp