---
- name: Configuración de la red IoT
  hosts: all
  become: yes
  vars:
    influxdb_version: "1.8.10"

  pre_tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar paquetes básicos
      apt:
        name:
          - snmp
          - snmpd
        state: present

  roles:
    - manager
    #- sensor
    #- camera

