---
- name: Descargar las mibs en el sistema
  shell: |
    apt-get install snmp-mibs-downloader -y
  tags: snmp

- name: Copiar el archivo de configuración de SNMP
  ansible.builtin.template:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
    mode: '0644'
  tags: snmp
  notify: Restart SNMP

- name: Copiar el archivo de input de SNMP en telegraf
  ansible.builtin.template:
    src: snmpd_telegraf.conf
    dest: /etc/telegraf/telegra.d/snmpd.conf
    mode: '0644'
  tags: snmp
  notify: Restart telegraf

